### ISSUE TITLE
Respect JSON property order

### ISSUE THREAD

**Issue by the-gigi** [sashirestela/simple-openai#110]
The classToJsonSchema doesn't preserve the order of fields when generating the schema. This can be significant when calling functions for the LLM to operate correctly. For example, order matters here:

```
{
  "instruction": ...,
  "action_based_on_instruction": ...
}
```

This can be done by adding an option to the JacksonModule initialization in JsonSchemaUtil.

From:
```
var jacksonModule = new JacksonModule(JacksonOption.RESPECT_JSONPROPERTY_REQUIRED);
```
To:
```
var jacksonModule = new JacksonModule(JacksonOption.RESPECT_JSONPROPERTY_REQUIRED,
            JacksonOption.RESPECT_JSONPROPERTY_ORDER);
```

**Comment by the-gigi** [comment]
@sashirestela if you're OK with it, I can open a PR.

**Comment by sashirestela** [comment]
Please, could you give us an example where the schema was not generated in the canonical order? In general I don't think the order of a function's arguments could be an issue if they are named.
Regarding your example, I think you should redesign it and split it into two or more functions. The library can handle many function calls in one shot.

**Comment by onhachoe** [comment]
This was actually a feature I wanted.
LLM generative answers are a little nuanced in that we'd want to blab about its reasoning before coming to a final answer.
In that regard, models mostly respect the order of arguments defined in the schema when generating its answers.

In the above example we have, LLMs seems to better values for `action_based_on_instruction` by reflecting on the previously generated `instruction` parameter. If the orders of arguments were reversed, it performs very poorly.

As to @sashirestela 's inquiry about separating this into two separate function call, we had generally a better success rate with single function call specified by being explicit with `tool_choice` parameter. Relying on multiple function call tends to be less reliable based on our observation.

We can kind of avoid this by doing two separate LLM dispatch, but our context input for LLM calls are rather large, so want to avoid that due to cost reasons.

Changes required to enable explicit ordering of parameters for json-schema should be rather minimal, and could be done with providing `JacksonOption.RESPECT_JSONPROPERTY_ORDER` to the jackson module initialization to respect `JsonPropertyOrder` annotation, and should be non-intrusive.

**Comment by sashirestela** [comment]
@onhachoe the change seems somewhat reasonable after reading your explanation. I'm not entirely convinced, but if this is helpful for both of you, go for it. On the other hand, if you find this project valuable there are a few ways you can show us your love, preferably all of them 🙂:
- Letting your friends know about this project 🗣📢.
- Writing a brief review on your social networks ✍🌐.
- Giving us a star on Github ⭐.

@the-gigi you could proceed with this specific change (don't touch any other part, please, because I'm working on a big refactoring for a new major release). Take in account that you will have to add more annotations to your  function's definition, as per this paragraph extracted from the library's documentation:

> Optionally: sort an object's properties according to its `@JsonPropertyOrder` annotation, if the `JacksonOption.RESPECT_JSONPROPERTY_ORDER` was provided (i.e. this is an "opt-in").

**Comment by sashirestela** [comment]
@onhachoe @the-gigi New release 2.3.3 was uploaded to Maven repositories.
