### ISSUE TITLE
Submit this library to the OpenAI community libraries page

### ISSUE THREAD

**Issue by mikehearn** [sashirestela/simple-openai#168]
See here:

https://share.hsforms.com/1y0Ixew-rQOOZisFfnhszVA4sk30

It means it'll be listed on the OpenAI website. At the moment only the newly unmaintained Theo library is there.

**Comment by sashirestela** [comment]
Hi @mikehearn thanks for using simple-openai! Yeah, I've tried several times since last year to include simple-openai on the OpenAI pages, but I'm afraid they are not interested in updating the list of community libraries, sadly.

A more effective way to support simple-openai and allow to be known for more people is:
- Letting your friends know about this project 🗣📢.
- Writing a brief review on your social networks ✍🌐.
- Giving us a star on Github ⭐.
