### ISSUE TITLE
Include Assistants API

### ISSUE THREAD

**Issue by sashirestela** [sashirestela/simple-openai#17]
Add the Assistants API (beta) https://platform.openai.com/docs/assistants/overview

@didalgolab Let me know if you would like to implement this API. If it is not possible, I could work on this.

**Comment by sashirestela** [comment]
@didalgolab, Thanks for working on this. Please, could you use this ticket for your changes?

Currently, the master branch has been updated with my changes for the other endpoints, and today I am going to update cleverclient (removing code related to immutable request objects) and immediately I will update simple-openai to use the latest cleverclient and to use the Lombok With annotation (simplifying our OpenAI.java interface and removing BodyPart usages).

I communicate you all these things to be in sync with you. Please, let me know if you have any concerns.

Do you think that it will be a good thing to create a Slack channel to have better communication? Or do you prefer to keep our communication by Github as currently? Or do you have another proposal?

**Comment by didalgolab** [comment]
I've added a PR https://github.com/sashirestela/simple-openai/pull/19 with my changes. Currently I'm waiting for you to integrate changes for https://github.com/sashirestela/cleverclient/pull/20 in the simple-openai project, because currently it doesn't compile after I have upgraded clever client to the latest version. But I'm sending the PR anyway, so that you can have a look already, and let me know issues you may have.

Regarding the proposal thank you, but I'm currently pausing any new development against OpenAI API - just wanted to finish the assistants part which I've already 95% complete.

**Comment by sashirestela** [comment]
@didalgolab I want to express my gratitude for all your help with this open source project. I really appreciate your amazing contributions.

Before you leave, I would like to know what are the pending parts in the Assistants API?

Finally, if you don't mind, could you give me some feedback on the project or my performance as the project owner?

**Comment by didalgolab** [comment]
@sashirestela Thank you for your kind words.

The Assistants API should be 100% complete, unless I've missed something - in which case let me know and I will try work that out. What I meant previously is that I had 95% ready, and managed to complete the remaining 5% on a day when I've pushed the PR.
However, I expect a lot of changes in the future to that API from OpenAI, because in current form the costs of using Assistants API are uncontrollable and unpredictable. In my opinion, it is barely usable right now.

Regarding the feedback, I'm not sure if I'm the right person to give one. Ultimately it all depends if the community can find this library useful. Anyway, here are my loose thoughts (but don't take them as a criticism in any way):
 - the library lacks build-in retry with exponential backoff (the official Python library has this),
 - error handling could be better, preferably with custom unchecked exception carrying the exact JSON error response returned by the OpenAI API, so the user can catch this exception, inspect its details, and act accordingly; maybe even separate dedicated exceptions for rate limit errors, and token limit exceeded errors;
 - for me it's debatable if `FunctionExecutor` should just throw `SimpleUncheckedException` when something goes wrong as it is now, or instead pass the error back to the LLM, to give the model chance to correct itself,
 - the Clever Client part is nice, but it looks a bit like reinventing a wheel (I get the impression that you were inspired by Feign, is that right?). Spring 6 introduces declarative HTTP services: https://www.baeldung.com/spring-6-http-interface, maybe those could serve as a good replacement for Clever Client? You would effectively have less code to maintain, and also Spring's WebFlux HTTP client is quite good.
 - support for Azure OpenAI API could be useful for some people,
 - also, I can see few ways to reduce number of Jackson annotations in your code, for example:
     * correcting property name to use underscore with e.g. `@JsonProperty("response_format")` can be replaced with just configuring `PropertyNamingStrategies.SNAKE_CASE` on the ObjectMapper level;
     * `@JsonInclude(Include.NON_NULL)` can be also configured on the ObjectMapper level;
 - I'm not quite sure that date-time response properties should be mapped to Long fields on the Java side (for instance the property `CharResponse -> private Long created;`), and actually, as you probably have already seen in my Assistants API code, I have used `ZonedDateTime` type with custom Jackson deserializer for date-time properties.

Overall, although I see areas in which the project is lacking, I find it also useful... Thank you for your service! 🫡

**Comment by sashirestela** [comment]
@didalgolab Thank you very much for your great observations, I am going to take them into account, for sure!
