### ISSUE TITLE
Q: Open to change coding style?

### ISSUE THREAD

**Issue by didalgolab** [sashirestela/simple-openai#9]
Hi, I like your library for its simplicity, and dependency-minimalism (not a particularly fond of introducing new cleverclient dependency though...), and I'm interested in contributing a couple of pull requests with bug fixes and features I found essential to be able to use your dependency in my projects.

But, before I do so, I have a question regarding the coding style. Would you be open to transitioning the project and the cleverclient dependency to use 4-space or tab instead of 2-space indentations?

**Comment by sashirestela** [comment]
Hi Mariusz. Thanks for your interest in collaborating on this project. Completely agree, simplicity and minimalism are key attributes for this. Two words about [Cleverclient](https://github.com/sashirestela/cleverclient), it was extracted from simple-openai because it is a different concern and I saw the opportunity to turn it in an independent library.

Regarding the indentations I think it is not a big issue, so no problem to move from 2 to 4 spaces.

**Comment by sashirestela** [comment]
@didalgolab  I'm going to change the indentation to use 4-space

**Comment by didalgolab** [comment]
Thank you! I'm going to issue some PRs in the nearest future. I think we can close this ticket.
